name: GitHub Release

permissions:
  contents: write
  discussions: write

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: wayland
          version: 1.0
      - name: build release
        run: cargo b --release --verbose
      - name: Compress
        run: tar -czvf ddnet-rs-amd64.zip ./target/release/ddnet-rs
      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: ddnet-rs-amd64.zip

  release-windows:
    runs-on: windows-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: build release
          run: cargo b --release --verbose
        - name: Compress
          run: powershell Compress-Archive ./target/release/ddnet-rs ddnet-rs-win64.zip
        - uses: actions/upload-artifact@v4
          with:
            name: windows-build
            path: ddnet-rs-win64.zip

  release:
    runs-on: ubuntu-latest
    needs: [release-linux, release-windows]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download linux
        uses: actions/download-artifact@v4
        with:
          name: linux-build
      - name: Download windows
        uses: actions/download-artifact@v4
        with:
            name: windows-build
      - name: Release on GitHub
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ddnet-rs-amd64.zip
            ddnet-rs-aarch64.zip
            ddnet-rs-win64.zip
